gcc Compressor\Compressor.c -o Compressor.exe
gcc Decompressor\Decompressor.c -o Decompressor.exe

.\Compressor.exe 5
.\Decompressor.exe output_5.bin

.\Compressor.exe 6
.\Decompressor.exe output_6.bin

.\Compressor.exe 7
.\Decompressor.exe output_7.bin

.\Compressor.exe 8
.\Decompressor.exe output_8.bin

.\Compressor.exe 9
.\Decompressor.exe output_9.bin

.\Compressor.exe 10
.\Decompressor.exe output_10.bin

.\Compressor.exe 11
.\Decompressor.exe output_11.bin

.\Compressor.exe 12
.\Decompressor.exe output_12.bin

.\Compressor.exe 13
.\Decompressor.exe output_13.bin

.\Compressor.exe 14
.\Decompressor.exe output_14.bin

.\Compressor.exe 15
.\Decompressor.exe output_15.bin

.\Compressor.exe 16
.\Decompressor.exe output_16.bin
